services:
  - type: web
    name: eye-blink-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    packages:
      - cmake
      - libgl1-mesa-glx
      - libglib2.0-0
      - libsm6
      - libxext6
      - libxrender-dev 